<?php

  /*----------------------------------------
   * @file
   * Cannon logo Integration
   *
   *----------------------------------------*/


/**
  * Implements hook_field_info().
  *
  * Provides the description of the field.
  */
 function cannon_document_field_field_info(){
   return array(
    // We name our field as the associative name of the array.
    'canon_document_url_text' => array(
      'label' => t('Document File Reference'),
      'description' => t('Selector given to the user to reference documents from the asset store'),
      'default_widget' => 'document_text',
      'default_formatter' => 'document_simple_text',
    ),
  );
 }

 /**
 * Implements hook_field_is_empty().
 *
 * hook_field_is_emtpy() is where Drupal asks us if this field is empty.
 * Return TRUE if it does not contain data, FALSE if it does. This lets
 * the form API flag an error when required fields are empty.
 */
 function cannon_document_field_field_is_empty($item, $field) {
   return empty($item['document_url_text']);
 }


/**
  * Implements hook_field_formatter_info().
  *
  * We need to tell Drupal that what type of formatter we have
  * for this field.
  *
  * @see cannon_logo_field_formatter_view()
  */
 function cannon_document_field_field_formatter_info() {
  return array(

    'document_simple_text' => array(
      'label' => t('Simple selector button'),
      'field types' => array('canon_document_url_text'),
    ),
  );
 }

/**
 * Implements hook_field_formatter_view().
 *
 *
 * - field_example_simple_text just outputs markup indicating the color that
 *   was entered and uses an inline style to set the text color to that value.
 * - field_example_color_background does the same but also changes the
 *   background color of div.region-content.
 *
 * @see field_example_field_formatter_info()
 */
 function cannon_document_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $element = array();

  switch ($display['type']) {
    // This formatter simply outputs the field as text and with a color.
    case 'document_simple_text':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#type' => 'html_tag',
          '#tag' => 'p',

          '#value' => '<div >' . $item['document_url_text'] . ' </div>',
        );
      }
      break;
  }

  return $element;
 }

/**
 * Implements hook_field_widget_info().
 *
 * One widget are provided.
 * - A simple text-only widget where the user mouses into the textbox and the modal box will pop up.
 *
 *
 * This widget types will eventually show up in hook_field_widget_form, where we will have to flesh it out.
 *
 * @see field_example_field_widget_form()
 */
 function cannon_document_field_field_widget_info() {
    return array(
      'document_text' => array(
        'label' => t('Selector Button'),
        'field types' => array('canon_document_url_text'),
      ),
    );
 }

 /**
 * Implements hook_field_widget_form().
 *
 * hook_widget_form() is where Drupal tells us to create form elements for
 * our field's widget.
 *
 * We provide one of three different forms, depending on the widget type of
 * the Form API item provided.
 *.
 */
 function cannon_document_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  //check if we are editing the the video content
  $title = "";
  $img = "/sites/all/modules/cannon_document_field/images/placeholder.jpg";
  if(isset($form['#node']->field_asset_store_document[LANGUAGE_NONE][0]['document_url_text'])){
    $src = explode('||||', $form['#node']->field_asset_store_document[LANGUAGE_NONE][0]['document_url_text']);
    if(isset($src[0])){
      $img = "/sites/all/modules/cannon_document_field/images/csa_icons-02.png";
    }
    if(isset($src[1])){
      $title = $src[1];
    }
  }

  //get the actual document
  $value = isset($items[$delta]['document_url_text']) ? $items[$delta]['document_url_text'] : '';

  $widget = $element;
  $widget['#delta'] = $delta;
  $class = array('canon-document');

  switch ($instance['widget']['type']) {

    case 'document_text':
      $widget += array(
        '#type' => 'hidden',
        '#default_value' => $value,
        '#attributes' => array('class' => $class ),
        '#suffix' => _cannon_document_field_get_suffix($delta, $img, $title),
      );
    break;
  }

  $element['document_url_text'] = $widget;
  return $element;

 }

 function _cannon_document_field_get_suffix($delta, $img, $title){


   return '<a href="#" class="document" >Select Document</a>
           <div class="description">Select Document</div>
           <div class="document-thumb">
              <img class="cannon-document" src="' . $img . '" width="95" height="80" />
              <div class="document-title">' . $title . '</div>
           </div>
           <div class="document-url"></div>
           <div class="document-modal">
             <div class="modal-header">
               <h2>Select a Document from the Asset Store</h2>
             </div>
             <div class="modal-body">
               <div class="document image-container"></div>
             </div>
             <div class="modal-footer">
               <br />
               <div class="column"><a href="#" class="modal-close">Close</a></div>
               <div class="column"><a href="#" class="modal-select">Select Document</a></div>
             </div>
           </div>';
 }


 /**
  * Implements hook_form
  **/
 function _cannon_document_field_request_data_from_asset_store(){

  $url = 'http://canoncache.trekkweb.com/data/api/document';
  $data = _cannon_document_field_api_call($url);
  $decoded = json_decode($data);
  $doc = "";

  if(count($decoded->data->document) > 0){
    $e = 0;
    foreach ($decoded->data->document as $key => $value) {
      //grab the next object as the large image
      $doc .= '<div class="document-cell document' . $e . '"><img width="130" height="80" data-url="' . $value->document . '" src="/sites/all/modules/cannon_document_field/images/csa_icons-02.png" /><div class="title">' .$value->title . '</div></div>';
      $e++;
    }
  }else{
    return "";
  }
  //return the HTML string
  print $doc;
  drupal_exit();
 }

 /**
 * Utility function
 *
 * @param $url, the url to request images
 */
 function _cannon_document_field_api_call($url){

    // Initializing curl
    $ch = curl_init($url);

    // Configuring curl options
    $options = array(
      CURLOPT_RETURNTRANSFER => true,
      CURLOPT_HTTPHEADER => array('Content-type: application/json') ,
    );

    // Setting curl options
    curl_setopt_array($ch, $options);

    // Getting results
    $result = curl_exec($ch); // Getting jSON result string
    return $result;
 }



/**
 * Implements hook_field_widget_error().
 *
 * hook_field_widget_error() lets us figure out what to do with errors
 * we might have generated in hook_field_validate(). Generally, we'll just
 * call form_error().
 *
 * @see cannon_logo_field_validate()
 * @see form_error()
 */
function cannon_document_field_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'cannon_logo_invalid':
      form_error($element, $error['message']);
      break;
  }
}


/**
 * Implements hook_menu().
 *
 * Provides a simple user interface that tells the developer where to go.
 */
function cannon_document_field_menu() {


  $items['get/image/documents'] = array(
    'title' => 'Get Documents',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_cannon_document_field_request_data_from_asset_store'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}


